name: Example - Deploy Cloud Run using gcloud
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to GCP as Infrastructure SA for deployment'
        uses: 'google-github-actions/auth@v2'
        with:
          export_environment_variables: true
          project_id : hack-team-finmatrix
          workload_identity_provider: projects/785558430619/locations/global/workloadIdentityPools/github-2023/providers/github-2023
          service_account: infrastructure@hack-team-finmatrix.iam.gserviceaccount.com  # Use your Infrastructure SA to manage resources

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy Cloud Run'
        id: deploy
        env:
          REGION: 'europe-west1'
          SERVICE_NAME: 'finmatrix-backend'
          WORKLOAD_SA_EMAIL: workload@hack-team-finmatrix.iam.gserviceaccount.com
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ var.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ var.AZURE_OPENAI_DEPLOYMENT_NAME }}
        run: |
          set -e
          gcloud run deploy "${SERVICE_NAME}" \
            --region "${REGION}" \
            --image "us-central1-docker.pkg.dev/hack-team-finmatrix/finmatrix-backend/finmatrix-backend:latest" \
            --service-account="${WORKLOAD_SA_EMAIL}" 
            --set-env-vars AZURE_OPENAI_API_KEY="${AZURE_OPENAI_API_KEY}",AZURE_OPENAI_ENDPOINT="${AZURE_OPENAI_ENDPOINT}",AZURE_OPENAI_DEPLOYMENT_NAME="${AZURE_OPENAI_DEPLOYMENT_NAME}"
          
          url=$(gcloud run services describe "${SERVICE_NAME}" --region="${REGION}" --format="value(status.url)")
          echo "url=${url}" >> "${GITHUB_OUTPUT}"
