name: Build, Push, and Deploy Frontend to Cloud Run
on:
  push:
    branches:
      - create_gcp_bucket
    paths:
      - 'frontend/**'


jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      REGION: 'europe-west1'
      SERVICE_NAME: 'finmatrix-frontend'
      WORKLOAD_SA_EMAIL: workload@hack-team-finmatrix.iam.gserviceaccount.com
      IMAGE_REPO: 'us-central1-docker.pkg.dev/hack-team-finmatrix/finmatrix-frontend/finmatrix-frontend'
      IMAGE_TAG: ${{ github.run_id }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Authenticate to GCP for Docker push'
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          project_id: hack-team-finmatrix
          workload_identity_provider: projects/785558430619/locations/global/workloadIdentityPools/github-2023/providers/github-2023
          service_account: workload@hack-team-finmatrix.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Create Artifact Registry repository'
        run: |            
          if gcloud artifacts repositories describe finmatrix-frontend --location=us-central1 &> /dev/null; then
            echo "Artifact Registry repository 'finmatrix-frontend' already exists"
          else
            gcloud artifacts repositories create finmatrix-frontend --location=us-central1 --repository-format=docker
          fi

      - name: 'docker config'
        run: 'gcloud auth configure-docker us-central1-docker.pkg.dev'

      - name: 'Build Image from frontend folder'
        run: |
          docker build -t $IMAGE_REPO:$IMAGE_TAG ./frontend

      - name: 'Push Image'
        run: docker push $IMAGE_REPO:$IMAGE_TAG

      - name: 'Authenticate to GCP for deployment'
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          project_id: hack-team-finmatrix
          workload_identity_provider: projects/785558430619/locations/global/workloadIdentityPools/github-2023/providers/github-2023
          service_account: infrastructure@hack-team-finmatrix.iam.gserviceaccount.com

      - name: 'Deploy Cloud Run'
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --region "$REGION" \
            --image "$IMAGE_REPO:$IMAGE_TAG" \
            --timeout=600s \
            --allow-unauthenticated \
            --service-account="$WORKLOAD_SA_EMAIL"